import type { Metadata } from 'next';
import './globals.css';
import React from 'react';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'CRUD Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <header className='shadow-md'>
          <div className='container mx-auto'>
            <div className='navbar'>
              <div className='flex-1'>
                <Link href='/login'>CRUD app</Link>
              </div>
              <div className='flex-none'>
                <ul className='menu menu-horizontal px-1'>
                  <li>
                    <Link href='/login'>Log In</Link>
                  </li>
                  <li>
                    <details>
                      <summary>Parent</summary>
                      <ul className='rounded-t-none bg-base-100 p-2'>
                        <li>Test-1</li>
                        <li>Test-2</li>
                      </ul>
                    </details>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </header>

        <main className='container mx-auto p-10'>{children}</main>

        <footer className='py-5 text-center text-xs text-gray-400'>
          <p>&copy; 2021 CRUD Next App</p>
        </footer>
      </body>
    </html>
  );
}
